sudo: required

language: node_js

env:
  PROJECT_NAME=alihm
  PORT=3000

node_js:
  - "8"

services:
  - docker

install:
  - npm install

before_script:
  # Unit tests
  - npm test
  - npm run build
  - docker build -t $DOCKER_USERNAME/$PROJECT_NAME --build-arg NODE_ENV=production .
  - docker run -d -e "NODE_ENV=test" -p $PORT:$PORT $DOCKER_USERNAME/$PROJECT_NAME

script:
  # Integration Tests
  - sleep 5
  - curl -I -m 5 localhost:$PORT
  - curl -m 5 localhost:$PORT/api/health

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $DOCKER_USERNAME/$PROJECT_NAME;
    fi
