sudo: required

language: node_js

env:
  PROJECT_NAME=alihm
  PORT=3000

services:
  - docker

before_script:
  - docker build -t $DOCKER_USERNAME/$PROJECT_NAME .
  - docker run -d -e "NODE_ENV=test" -p $PORT:$PORT $DOCKER_USERNAME/$PROJECT_NAME

script:
  # Integration Tests
  - sleep 5
  - curl -I -m 5 localhost:$PORT
  - curl -m 5 localhost:$PORT/api/health

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $DOCKER_USERNAME/$PROJECT_NAME;
    fi
