
image:
  repository: ali92hm/alihm
  tag: stable
  replicaCount: 2
  imagePullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  host: alihm.net
  redirectWWW: true
